### PR TITLE
Fixes #86

### LINKED ISSUE #86: True/False params are not output when executing a command
Hey guys, I have an argument that looks like this:
```
main_options_group.add_argument('--my_optional_arg', default=False, action='store_true')
```

This is correctly stored as a ScriptParameters object when I tick the checkbox in the Wooey interface.  However when Celery executes the command it does not include --my_optional_arg in the command that is executed.

Looking at the source, it seems that `param.get_subprocess_value()` does not return a "value" for the param, causing the condition in the "if" statement on line 79 of utils.py to fail and ultimately preventing the param from being output correctly. 

See my pdb log below.  You can see that after executing line 78 "subproc_value" is None, despite param.value being True

```
(Pdb) l
 73  	        if subproc_dict is None:
 74  	            continue
 75  	        subproc_param = subproc_dict['parameter']
 76  	        if subproc_param not in param_dict:
 77  	            param_dict[subproc_param] = []
 78  ->	        subproc_value = subproc_dict.get('value', None)
 79  	        if subproc_value:
 80  	            param_dict[subproc_param].append(subproc_value)
 81  	    for param, values in param_dict.items():
 82  	        for value in values:
 83  	            if param:
(Pdb) n
> .../wooey/backend/utils.py(79)get_job_commands()
-> if subproc_value:
(Pdb) subproc_value
(Pdb) param._value
u'true'
(Pdb) param.value
True
(Pdb) param.get_subprocess_value()
{u'parameter': u'--my_optional_arg'}
```

### PR DESCRIPTION
**Pull request by hottwaj**
Slight variation to what @Chris7 mentioned on Friday.  

I wanted to add a test to check for this behaviour but from a (very) quick glance through couldn't work out how to use the API to add a script with an appropriate parameter - any hints appreciated!

### CODE REVIEW

**Comment by Chris7** [comment]
Hey @hottwaj 

Thanks for the fix. Could you add a test to make sure the desired use case is handled correctly? Just adding a boolean field to the choices script or something like that.

**Comment by hottwaj** [comment]
Sure Chris, I will do when I have a moment.

**Comment by Chris7** [comment]
Thanks. I'm also short on time otherwise I'd just do it :). Currently trying to meet some deadlines for 2 papers I'm trying to get out.

**Comment by Chris7** [comment]
Hey @hottwaj, did you ever have a chance to do tests for this?

**Comment by hottwaj** [comment]
Hey Chris, I know it's not a big job but I've not been able to set any time
aside for it as I've since been working on other projects, and I'm going
away shortly so can't really look at it over the next 3 weeks...  Sorry -
not very helpful I know...

**Comment by Chris7** [comment]
No problem. I  just wanted to check with you before I looked into it.

**Comment by Chris7** [comment]
I think this might be a better way to go about it:

https://github.com/wooey/Wooey/commit/ae97163b2e78437c7b9c42f3f713432b59787d7d

It removes the parameter from the model and I'd rather check if we have both the param & values instead of values first.

**Comment by Chris7** [comment]
This is fixed via ae97163

**Pull request closed without merging**
