### PR TITLE
Update details and fix examples on aws.rst 

### PR DESCRIPTION
**Pull request by pauricthelodger**
The django-storages-redux is now the canonical version of django-storages.
Also, Github's web edit mode added the new line at the end of the file.

### CODE REVIEW

**Comment by pauricthelodger** [comment]
I've changed this slightly because I noticed there were some other edits to do on the page and decided to offer them as a combined PR.

**Comment by Chris7** [comment]
This is bizarre, why are the newlines missing in the diff but not on master?

**Comment by pauricthelodger** [comment]
@Chris7, yeah it's a bit weird! I figured it was that the lines got joined during a multiline edit or something (been hit by that a few times myself). Definitely on master, I'm afraid, as I noticed it in readthedocs originally and double-checked after git clone to local.

wooey-1
wooey-2

Adding myself to the contributors as you suggested in #173 but wondering if you'd like me to change & update this PR to include a few other updates to pages in the docs before accepting it rather or is it better for me to make others as I go along?

**Comment by Chris7** [comment]
I'd welcome any additional changes! I'd prefer to keep things somewhat nice looking in the history, so another PR would be better for me.

**Pull request merged**
