### PR TITLE
Documentation (and ReadTheDocs support)

### PR DESCRIPTION
**Pull request by mfitzp**
This PR is a start at implementing documentation for Wooey. It's initially focusing on auto API documentation + getting a nice tidy set up for that. Will add the base outline for install copying and re-formatting from README.md before merging.

### CODE REVIEW

**Comment by mfitzp** [comment]
This branch is now auto-building here: http://wooey.readthedocs.org/en/latest/

**Comment by Chris7** [comment]
It looks awesome. I'll see what I need to do to tie into this.

**Comment by mfitzp** [comment]
I've just updated it with bits for the submodules (e.g. views.authentication) so the API documentation is now a lot more complete. Should we merge? We can start adding in the documentation on the functions then.

At the moment RTD is pulling from this branch but I'll update. If you sign up on RTD I'll add you as a maintainer.

**Comment by mfitzp** [comment]
With the updated commits the build on RTD now passes without errors (needed to create a dummy `SECRET_KEY`) which is passed in from the run environment.

Some pages (e.g. http://wooey.readthedocs.org/en/latest/views.html ) don't appear to be correctly rendering their content — I've seen this before but I can't remember for the life of me why.

**Comment by mfitzp** [comment]
@Chris7 I've updated the documentation with all the content from the current `README.md` so I think it's good to go. Happy to see it merged (once conflicts are fixed)?

**Comment by Chris7** [comment]
I don't see where RTD requests a SECRET_KEY. Can't you just link your github account and go through the import process there?

**Comment by mfitzp** [comment]
It's in the automodule parsing stage (Sphinx): to generate the docs it has to import the files which dies when it gets to the point requesting the `SECRET_KEY` to be set. For some reason unless I put it where it (currently) is it dies. But I would rather not have that there since it's pointless (for production).

I'll have another look and see if I can see a way around it.

**Comment by mfitzp** [comment]
The latest changes solve the problem by adding an addition `docs_settings.py` file that provides the `SECRET_KEY` for building on RTD. It seems to be building without errors now. Happy with this approach?

**Comment by mfitzp** [comment]
I give up. RTD is now giving an `AppRegistryNotReady: Models aren't loaded yet.` error but the docs are building. The errors means a few attributes are missing from some models (e.g. `Script.script_path`) but I can't see a logic to the source of problems. I've tried to solve the above in various ways none of which work: it's incredibly annoying trying to debug on a remote service (can't replicate this problem with local Sphinx so will need to set up an entire RTD install locally). 

So, I'm happy to merge and pick off these errors later... (open bug to track) I don't think this is a reason to hold off release.

**Comment by Chris7** [comment]
Can you post the traceback?

**Comment by mfitzp** [comment]
It's pretty long but it starts with...

    /home/docs/checkouts/readthedocs.org/user_builds/wooey/checkouts/latest/docs/index.rst:45: WARNING: toctree contains reference to nonexisting document u'dev_install'
    /home/docs/checkouts/readthedocs.org/user_builds/wooey/checkouts/latest/docs/models.rst:8: WARNING: autodoc: failed to import attribute u'Script.script_path' from module u'wooey.models.core'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/wooey/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
        obj = self.get_attr(obj, part)
      File "/home/docs/checkouts/readthedocs.org/user_builds/wooey/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
        return safe_getattr(obj, name, *defargs)
      File "/home/docs/checkouts/readthedocs.org/user_builds/wooey/envs/latest/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
        raise AttributeError(name)
    AttributeError: script_path

...if you can sign up for readthedocs.org and let me know your username I can add you as an admin on the project so you can see the builds directly (there is a lot of output).

**Pull request merged**
