### PR TITLE
add localizations for Japanese

### PR DESCRIPTION
**Pull request by manicmaniac**

### CODE REVIEW

**Comment by Chris7** [comment]
This is awesome! Thank you for the contribution. I noticed some places were missing translations. Could you rebase from master and fill in the gaps please?

**Comment by manicmaniac** [comment]
Actually I simply copied a message file from other language on my first commit.
Right now I run `manage.py makemessages` and translate the generated file.
Yet, if `fill in the gaps` means more aggressive translation like putting missing `{% trans %}` tag in some files, I am ready to do it.

**Comment by Chris7** [comment]
I believe I've put in {% trans %} tags everywhere there need to be (and put them in for the models as well for the admin). If you see places it is missing through common use please feel free to notify me/fix them. I meant rebase the code on the current master, and then regenerate the messages file (it should just append the new ones and keep your old translations) and add any new terms that were missed.

Once again, thank you very much for this. I think it's awesome Wooey will have this support!

**Comment by manicmaniac** [comment]
Oops, It seems I was mistaken about that.
Wait a moment, I will fix up all the mess.

**Comment by Chris7** [comment]
I think you need to set an upstream to the main wooey repo from your fork, and rebase your master on that. Then rebase these commits on top of that master. The new commits are changing files that are already changed to contain the translation tags and causing conflicts.

**Comment by Chris7** [comment]
Thanks @manicmaniac!

**Pull request merged**
