### PR TITLE
PEP8 fixes via pep8ify

### PR DESCRIPTION
**Pull request by mfitzp**
A test-run using pep8ify to perform PEP8 fixes (minus the line length) automatically. The remaining issues are mostly due to redundant imports which are easier to fix.

Ref issue #40

### CODE REVIEW

**Comment by mfitzp** [comment]
@Chris7 should I merge this or wait for the other changes (might be easier to re-pep8ify over the top of the new filesystem changes than try and fix the conflicts).

**Comment by Chris7** [comment]
@mfitzp I'd rather pep8ify after changes are put in. Seems silly to cause merge conflicts over cosmetic changes to me.

**Comment by mfitzp** [comment]
Cool. Will keep this open til we get a window and re-do.

**Comment by mfitzp** [comment]
Force updated this branch to current master will re-apply PEP8 after final merge and re-open a new PR.

**Pull request closed without merging**
