### PR TITLE
Tweak to allow a "TextField" to be used instead of a "CharField" for parameter inputs

### PR DESCRIPTION
**Pull request by hottwaj**
Tweak to allow a "TextField" to be used instead of a "CharField" for parameter inputs (user has to manually change the "Form field" setting in the admin).

No worries if this is not a feature you want to add!

### CODE REVIEW

**Comment by Chris7** [comment]
Hey @hottwaj.

Thanks for your PR. I've been thinking a bit about how to do this best. One idea is to have a widget creator in the admin the user can link the form field to. That would define its own css/etc. and be more reusable as well as customizable. I'm not sure of the best method at the moment -- until then I'm probably going to sit on this.

**Comment by hottwaj** [comment]
Nice plan Chris, makes more sense than adding random tweaks than mine!
Cheers

**Comment by hottwaj** [comment]
I meant "random tweaks *like* mine"...

**Comment by hottwaj** [comment]
Removing this as it was only a quick hack...

**Comment by Chris7** [comment]
The planned way to go about this is through a WooeyWidget model that the user can link a ScriptParameters instance to. It can't be a simple html layout because we have to deal with initial data/etc. I'm thinking of having it just be a field where you define a class (like forms.TextArea), and a place to enter attributes to overload the widget_attr dict with.

**Pull request closed without merging**
