### PR TITLE
i18n: Add translation files for de, fr, nl.

### PR DESCRIPTION
**Pull request by mfitzp**
To begin process of adding working i18n these files add base
translations from the current strings. They are machine translated
using Google's service (https://translate.google.com/toolkit/) and
so likely broken.

The NL looks vaguely right to my limited knowledge but I will check
them all with native speakers.

### CODE REVIEW

**Comment by Chris7** [comment]
Awesome! We can add in a reference to LANGUAGE_CODE in our docs for people to enable these.

**Comment by mfitzp** [comment]
Do you know much about Django translations? I've got the `.po` files compiling to `.mo` and they work, but the `.mo` files are gitignored and reading around it suggests you don't include them.

Do we need to tell people to run the admin command (`compilemessages`) or is that automated somehow?

**Comment by Chris7** [comment]
I've used them on 2 sites before, but that was sometime ago. I recall you need to makemessages (for the translators to fill out), then compile via compilemessages (to compile what the translators did). I think it would be beneficial to include both, so translators can fix our mistakes via PRs.

**Comment by mfitzp** [comment]
Apparently since `.mo` files are binary you're "not supposed" to include them in the repo — but then you need gettext for that bit to work which isn't great. The same point was actually raised as an [issue against Django](https://code.djangoproject.com/ticket/23321) but they are still in [as here](https://github.com/django/django/tree/master/django/conf/locale/ar/LC_MESSAGES). 

I've tested using `django-admin compilemessages` from an install where it works and the UI is correctly foreign so I'll add the `.mo` files to this repo.

I'll add the note about `LANGUAGE_CODE` to the documentation and to add `django.middleware.locale.LocaleMiddleware` for automatic locale switching based on the browser.

**Comment by mfitzp** [comment]
File "/usr/local/lib/python2.7/site-packages/wooey/views/wooey_celery.py", line 27, in <module>
        WooeyJob.COMPLETED: SPANBASE.format(_(u'Success'), 'success glyphicon-ok'),
      File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 144, in __bytes_cast
        return bytes(func(*self.__args, **self.__kw))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 4: ordinal not in range(128)

**Comment by mfitzp** [comment]
I've added a few more missing strings and fixed their translations to the best of my abilities. Should now work out of the box for the three languages.

screen shot 2015-09-08 at 17 47 05

screen shot 2015-09-08 at 17 47 14

Should be a good base for fixes from users and new languages.

**Comment by Chris7** [comment]
One caveat to this is returning things via JSON/javascript, which need to be the gettext_lazy form and not the ugettext_lazy form since the latter will be a proxy object. Similarly, it will result in our js being translated as things like Proxy Object <memory_address>. Not sure if we hit these cases, about to look at it.

**Comment by mfitzp** [comment]
Is there another workaround for unicode with gettext_lazy then? Otherwise we'd be prevented from using unicode which is most languages out the window :)

**Comment by Chris7** [comment]
Yeah, you can use force_text to force evaluation of the proxy object, you can see I've done this in authentication.py

**Comment by Chris7** [comment]
You can check it out here: https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.encoding.force_text

I ran into this issue a few times before using js/JSON for my request/response cycles.

**Comment by Chris7** [comment]
We can make a helper function that combines those force_text(ugettext_lazy(str)), like w_(str)

**Comment by mfitzp** [comment]
Isn't gettext_lazy also a proxy object? I'm not seeing the difference... the definitions look like this: 

    gettext_lazy = lazy(gettext, str)
    ugettext_lazy = lazy(ugettext, six.text_type)
    pgettext_lazy = lazy(pgettext, six.text_type)

I thought the `_lazy` indicated that they were all proxies?

I agree on the helper function though otherwise the JSON stuff is going to be horrible. What does the `w_` stand for though? :)

**Comment by Chris7** [comment]
Sorry you are correct. But we should check out what isn't being evaluated prior to being serialized. Might just be a useful tidbit to keep in mind for the future.

**Comment by Chris7** [comment]
I'm good to merge when you are.

**Comment by mfitzp** [comment]
Great, we're done. I'll tag the release and push it onto PyPi :+1:

**Pull request merged**
