### PR TITLE
Fixed the TypeError __init__() takes exactly 5 arguments (4 given) pr…

### PR DESCRIPTION
**Pull request by bykof**
…oblem

In Django 1.9 you get following error: 
    TypeError at /wooey/
    __init__() takes exactly 5 arguments (4 given)

This is because you use the wrong decorator. This commit will fix it

### CODE REVIEW

**Comment by Chris7** [comment]
This will break < 1.9 compatibility. We use a custom tag written in the same file. Can you put in a fix that handles both < 1.9 and this? Ideally, something with a unit test (we don't cover this file yet -- we need to!)

**Comment by bykof** [comment]
I will try my best! The simple_assignment_tag is written not very well... I understand what you wanted to do with this wrapper, but it seems to make a lot of problems. 

Anyway... I will have a look at this function and will try to fix it.

**Comment by Chris7** [comment]
We took it from a gist. It's probably the changes to TagHelperNode in 1.9 that is crashing it, but a simple version check for what function to return in it is probably all that's needed. Like:
```
return dec if DJANGO_VERSION < DJ19 else self.simple_tag
```

**Comment by bykof** [comment]
Oh no... just... please don't do this. I will have a look and will implement it in a "beautiful" route :D

**Comment by bykof** [comment]
I got it. I also tested it with django 1.8 and 1.9 everything worked very well.

**Comment by Chris7** [comment]
Thanks for your commits! I see two issues though: 
1. This still breaks for users that have custom templates on Django < 1.9. 
2. assignment_tag is depreciated for Django 2.0 so this is just a stopgap fix.

I'm much more comfortable asserting the use of assignment_tag for < 1.9 and simple_tag for >= 1.9 just changing which decorator is applied via a version check.

**Comment by Chris7** [comment]
But I agree that removing the custom library tag is a good thing

**Comment by bykof** [comment]
Lets say in the new version: 1.0 you say it will be not supported anymore to use the old custom templates and the users have to adjust their custom templates.
The other thing with the version and the deprecation of assignment tag. 
You can edit this commit and add a version check for the assignment tag.

**Comment by bykof** [comment]
@Chris7 I have updated this pull request with the custom django supports.

**Comment by Chris7** [comment]
No offense intended, but I'm going to merge in a solution I think is best. My reasons are that the proposed change is still backwards incompatible since the assignment fallback doesn't occur. I also do not think a depreciation policy is yet merited for Wooey. It really boils down to the issue that Django < 1.9 did not have a tag that supported assignment and an output fallback. I feel the best solution is the custom decorator (which is just a copy/paste job from Django's source) for < 1.9 and the simple_tag for >= 1.9. It's literally 3 lines of code and breaks no existing compatibility.

**Comment by Chris7** [comment]
Addressed in #113.

**Pull request closed without merging**
