### PR TITLE
Script url changes

### PR DESCRIPTION
**Pull request by Chris7**
This addresses an issue raised in #43. It creates a new scheme for script urls and versions and adds in a dropdown box for the user to select older scripts.

### CODE REVIEW

**Comment by mfitzp** [comment]
Great stuff on this @Chris7 

I was thinking about this over the weekend (need to get a life) and was wondering whether we should be using the script version (from the argparse dict) to specify the version in the model. At the moment the version is an incrementing number which doesn't neccessarily have any relation to the version of the script, rather the "number of times it's uploaded". When I was trying to debug a script I ended up on version 20-odd which means 19 dud entries in the database. A version string would be more meaningful.

Incrementing to a new version could be achieved manually by adjusting the value in the box. We can then use standard Python version-comparisons to determine the latest?

Also, would it be worth adding a `is_latest` parameter to the script model to mark the 'latest' version of the script. That way we would add `is_latest=True` as a default manager to simplify filtering on that without checking versions directly.

**Comment by Chris7** [comment]
The created time would by default be the latest one, so I think that field would be redundant. The is_active flag can be used to disable a given version.

**Comment by mfitzp** [comment]
Good point on `created_time` and `is_active` as it would also allow multiple versions of scripts to be kept 'active' by setting them `is_active` which would be nice for some uses.

I'm wondering if we should be splitting out the versioning into a separate model `ScriptVersion` - it's generally a bad idea in databases to duplicate data and at the moment we're going to end up with multiple copies of `script_name` `script_group` `script_description` `script_order` `user_groups` etc. as new versions are uploaded. This also prevents linking any other model to a `Script` (for example favorites will be eliminated every time a script is updated).

This would take a bit of refactoring (including in the UI) to access `script.script_version` data though.

**Comment by Chris7** [comment]
I didn't think about favorites. They will break with this. In the script addition we could update what the favorites point to to solve that.

I'm not sure about ScriptVersion as a model. It seems like whatever it should be holding would end up describing a script, and be redundant as well. script_path is really the part that is changing between versions, with versions/iterations just reflecting the time points. So it's more like a revision history than a data duplication.

**Comment by Chris7** [comment]
Well, it looks like version isn't an option for python3 with argparse.

**Comment by mfitzp** [comment]
Version is still there [but as a parameter](https://docs.python.org/3/library/argparse.html#module-argparse) in Python 3 (search for `--version` on that page). Strange that it was changed in the API but something we can pick up?

**Comment by Chris7** [comment]
Oh nice, we can just check for the action there. It'd be a clinto thing.

**Comment by mfitzp** [comment]
Some general waffle on the `ScriptVersion` vs. single model that I've been thinking over —I'm going to make the case *for* the model since I can see benefit of it, but I'm nowhere near as convinced as it might sound.

There being relatively little in the `ScriptVersion` model is the reason it's useful - it's holding the few things that change. Looking at the current model (+the documentation PR) the models would be something like:

    ScriptVersion
        script_path
        documentation
        ?execute_full_path
        ?save_path
        script_version
        script_iteration
        ?is_active
        (created_date, modified_date)
    
    Script
        slug
        script_name
        script_group
        script_description
        script_order
        ?execute_full_path
        ?save_path
        ?is_active
        (created_date, modified_date)    

I don't think we should base our judgement on favourites(!) but keeping everything in one model (with duplicates for versions) complicates this a bit — say you mark a script as favourite, then it's updated. Do you duplicate the favorite to the new script (you now have 2 favorites... 5 favorites... 15 favorites) or replace (you now have 1 pointing to the wrong version).

It also makes it trickier in the UI to show multiple versions: they will be listed as separate scripts (e.g. on the front page) - this might be what we want, but we can't easily provide a summary of "this script has N versions", or "there are N scripts in this script_group" because doing so we'll have to also calculate uniqueness on the slug column. 

Other things like tags will need to be duplicated also. I've been toying with the idea of 'suggested-inputs' tying outputs from one script to the input of another (*did somebody say workflows...noooo!*) and these sorts of things would also need to be duplicated.... in fact anything relating to an individual script. A few updates later and the database is full of replicated data (a bad thing).

The argument against all of this of course is that many of these things might change between versions and would need to be tracked on the `ScriptVersion` model anyway.

I think it would probably be useful to try and imagine how the duplicate versions would appear from the UI side of things and how we can implement that with both model structures and pick the simplest?

*That said* we could just merge and release with it as it is and tackle this further down the line when implications of different approaches becomes more apparent. It will all be manageable with a migration anyway

**Comment by Chris7** [comment]
To me, a favorite is a script -- not the version. You favorite common activities to promote them to the front of the list. Additionally, you may select any older version of the script currently via the dropdown tab (in case you haven't seen that, I don't think you have now that you mention the UI):

download

Given that, I support updating references to reflect the desired version (tags/favorites/etc.). If the latest version is deleted, you reset all those references to the appropriate version and so on. These can all be in a single method to keep things simple and updated via signals.

**Comment by Chris7** [comment]
For this:

I've been toying with the idea of 'suggested-inputs' tying outputs from one script to the input of another (did somebody say workflows...noooo!) and these sorts of things would also need to be duplicated.... in fact anything relating to an individual script. 

I've been considering ScriptParameters, and testing which need to be updated for versioning. That way, we can tie things such as thing together without duplication.

**Comment by Chris7** [comment]
Also for workflows:

We can already tell what is an input/output and let the users connect whatever parts they want together. If they connect the wrong pipes it's their fault and they should have an error message anyways to guide them once the script execution fails. And if we have savable/loadable/shareable workflows, then they can start with a template anyways.

**Comment by mfitzp** [comment]
Risking sounding like a stuck record here but if (we agree) we favorite on the Script having the versions in the same table makes for a lot of potential complication when adding/removing scripts. When adding a new version of the script we will have to update the favorites to point to the new model. What do we do if the latest script is disabled? Catch that and move all the favorites to a previous version. Then re-enabled? Shift it back. It just seems like a lot of faff compared to having the favorite against the script, and allowing the version churn to happen in a separate model.

If we have two active versions of a script the favorite can only point to one, so retrieving the other requires a separate step of logic (in Python) and query rather than being able to keep this to the database. For example the `def get_previous_versions(self)` is currently going to fire on every single script displayed on a list (front page). That's a lot... If we normalised into a separate model we can get all that information in a single query at page load (and without pre-processing it).

Also, if we hang this off in a separate model we can also have a single page in the admin for a script, with a list of all the iterations/versions of the script shown below it to be independently added/removed and enabled/disabled. I think it would simplify the `def load_scripts()` block a lot also: you could tag is_latest (or manually bind to the Script model as a OneToOne) and replace that entire block with a single query.

Anyway, that's my thoughts. If you're not convinced feel free to merge this as it is something we can come back to later if we need to! :+1:

**Comment by Chris7** [comment]
@mfitzp So the fundamental issue is we are using a FK to track something that is not a reliable FK. One way to address this would to flip the current logic around. Currently, we create a new database entry of the new script, whereas we could make a new entry of the old model. So instead of cloning and updating, we clone to keep the revision history and update the old model. This would keep FKs pointing in the right place and tags/etc.

But I'm coming to agree with you. I didn't realize how you were envisioning things pointing at eachother. Keeping scripts as a unit we care about (after all, we don't care so much about which file it is, just that it has the functionality of the script) and alter a secondary model to keep it tracking would save us some trouble down the road. It would also help with dealing with recursions we currently have with model saving. 

With this new setup, we have a Script FK on ScriptVersion, with the resolutions needed to execute the script being handled at runtime. We can handle versioning history with jobs by adding a script_version field so we can recreate old versions. ScriptVersion will be duplicated for new versions/iterations. If a version is updating, we create a new ScriptVersion and change what the script is referencing. We still have issues of selecting the correct one under various circumstances, but it's a bit less of a burden than things we are linking to scripts.

**Comment by Chris7** [comment]
@mfitzp If you try this -- make sure you copy your database because as of now, it will destroy information.

**Comment by Chris7** [comment]
Should be ok, but backup in case for this migration.

**Comment by mfitzp** [comment]
Crikey. That's some nice work though! 

One (final) thought... instead of the `default_version` parameter on the ScriptVersion we could define a default_version on the `Script` as a `ForeignKey` (with `null=True`). This would allow immediate access to the latest version when querying Scripts. We can auto-populated that field with a on-save hook on `ScriptVersion` (so every time a new `ScriptVersion` is saved that field will be updated).

:+1: on changing from `settings.WOOEY_SCRIPTS` to building in the utils - the previous method meant that addition/removal wasn't always immediate.

**Comment by Chris7** [comment]
For WOOEY_SCRIPTS as well -- the real issue was signals are not propagated to distributed apps so it was poor design. I was trying to make a poor man's cache -- if they want more speed, they can just use cacheops/johnny cache/etc.

**Pull request merged**
